load("extensions/rbac.star", "add_v1_based_permission", "add_v1only_permission")

# playbook_dispatcher instead of playbook-dispatcher because '-' isn't a valid identifier character in Kessel. The preprocessor automatically replaces unallowed characters with underscores, so this matches the autogenerated schema.
add_v1_based_permission("playbook_dispatcher", "playbook_dispatcher", "remediations_run", "read", "playbook_dispatcher_remediations_run_view")
add_v1_based_permission("playbook_dispatcher", "playbook_dispatcher", "tasks_run", "read", "playbook_dispatcher_tasks_run_view")
add_v1_based_permission("playbook_dispatcher", "playbook_dispatcher", "config_manager_run", "read", "playbook_dispatcher_config_manager_run_view")

# Placeholders for V1 permissions to be removed once the migration is complete
add_v1only_permission("playbook_dispatcher", "playbook_dispatcher_run_read")
add_v1only_permission("playbook_dispatcher", "playbook_dispatcher_run_write")
